### ISSUE TITLE
Doesn't compile on rust 1.68

### ISSUE THREAD

**Issue by Divide-By-0** [nakabonne/rhack#9]
I get these errors
```
error[E0432]: unresolved import `clap::Clap`
 --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/cmd/edit.rs:9:5
  |
9 | use clap::Clap;
  |     ^^^^^^^^^^ no `Clap` in the root

    Building [=========================> ] 55/56: rhack(bin)      error[E0432]: unresolved import `clap::Clap`
 --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/cmd/undo.rs:7:5
  |
7 | use clap::Clap;
  |     ^^^^^^^^^^ no `Clap` in the root

    Building [=========================> ] 55/56: rhack(bin)      error[E0432]: unresolved import `clap::Clap`
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/cmd/mod.rs:10:25
   |
10 | use clap::{AppSettings, Clap};
   |                         ^^^^ no `Clap` in the root

error[E0432]: unresolved import `clap::Clap`
 --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/main.rs:7:5
  |
7 | use clap::Clap;
  |     ^^^^^^^^^^ no `Clap` in the root

error: cannot determine resolution for the derive macro `Clap`
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/cmd/edit.rs:14:10
   |
14 | #[derive(Clap, Debug)]
   |          ^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

    Building [=========================> ] 55/56: rhack(bin)      error: cannot find attribute `clap` in this scope
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/cmd/edit.rs:19:7
   |
19 |     #[clap(short, long)]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot determine resolution for the derive macro `Clap`
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/cmd/undo.rs:11:10
   |
11 | #[derive(Clap, Debug)]
   |          ^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

    Building [=========================> ] 55/56: rhack(bin)      error: cannot find attribute `clap` in this scope
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/cmd/undo.rs:14:7
   |
14 |     #[clap(short, long)]
   |       ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

error: cannot determine resolution for the derive macro `Clap`
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/cmd/mod.rs:26:17
   |
26 | #[derive(Debug, Clap)]
   |                 ^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

    Building [=========================> ] 55/56: rhack(bin)      error: cannot find attribute `clap` in this scope
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/cmd/mod.rs:27:3
   |
27 | #[clap(
   |   ^^^^
   |
   = note: `clap` is in scope, but it is a crate, not an attribute

    Building [=========================> ] 55/56: rhack(bin)      error[E0599]: no variant or associated item named `parse` found for enum `App` in the current scope
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/main.rs:13:26
   |
13 |     if let Err(e) = App::parse().run() {
   |                          ^^^^^ variant or associated item not found in `App`
   |
  ::: /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rhack-0.1.0/src/cmd/mod.rs:34:1
   |
34 | pub enum App {
   | ------------ variant or associated item `parse` not found for this enum
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following traits define an item `parse`, perhaps you need to implement one of them:
           candidate #1: `Parser`
           candidate #2: `TypedValueParser`
           candidate #3: `combine::parser::Parser`
           candidate #4: `combine::parser::ParseMode`

    Building [=========================> ] 55/56: rhack(bin)      Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
    Building [=========================> ] 55/56: rhack(bin)      error: could not compile `rhack` due to 11 previous errors
error: failed to compile `rhack v0.1.0`, intermediate artifacts can be found at `/tmp/cargo-install4qKSfR`
```
rustc --version
rustc 1.68.0 (2c8cc3432 2023-03-06)

**Comment by simonsan** [comment]
Should compile again, check #10 and clone the repo to install from there.

Fixed in #10 (closed due to branch rename)
Fixed in #11
